name: centipede
author: Caleb Morris <caleb.morris.g@gmail.com>
homepage: https://github.com/CalebMorris/centipede
description: Dart recreation of the classic arcade game "Centipede"
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  async: any
  browser: '>=0.9.0 <0.10.0'
  math: any
